---
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
Name: mysite
After: 'framework/*','cms/*'
---
SSViewer:
  # display template filenames as comments in the html output
  source_file_comments: false
  # This boilerplace suggests using only the mysite folder without a theme
  # if you want to set a theme, change the 2 lines below
  theme_enabled: false
  # theme: 'simple'
MySQLDatabase:
  connection_charset: 'utf8'
GDBackend:
  default_quality: 100
SiteTree:
  nested_urls: true
  # Disable creating of default pages (like home) on /dev/build
  # create_default_pages: false
Email:
  admin_email: 'info@stripecon.eu'
SiteConfig:
  extensions:
    - 'mysiteSiteConfigExtension'
LeftAndMain:
  extensions:
    - 'mysiteLeftAndMainExtension'
BetterRequirements_Backend:
  compile_in_dev: false
  compile_in_test: false
---
Only:
  environment: 'dev'
---
SSViewer:
  source_file_comments: true
DataObjectAnnotator:
  enabled:
    true
  enabled_modules:
    - mysite
